#' Observed versus Predicted
#'
#' Draw observed vers. predicted graphics.
#'
#'
#' ObsPred file is generated by *fingR::JAGS.summary* and contains: observed (obs), predicted values.
#' stats is generated with *fingR::eval.groups* function contains prediction quality statistics and value calculation Type (mean, median...) and source Group information.
#'
#' @param obs A numeric vector with observed values. [not avalaible]
#' @param pred A numeric vector with predicted values. [not avalaible]
#' @param data A data.frame with observed and predicted values. [not avalaible]
#' @param path Connection to the folder were the ObsPred and stats files are located and connection open for writing the test results data.frame, "" save the file at working directory, if not set (default) the data.frame is not saved.
#' @param note A character string to add a note at the end of the file name (not set - default).
#' @param acceptance A numerical value to draw confidence interval around the 1:1 line.
#' @param labels A boolean, TRUE to display samples names with *geom_labels* function (FALSE, default).
#' @param text A boolean, TRUE to display samples names with *geom_text* function (FALSE, default).
#' @param stats A boolean, TRUE to display modelling quality statistics. (FALSE, default).
#' @param pt.coulour Point colour aesthetics.
#' @param ln.coulour Line colour aesthetics.
#' @param pt.pch Point shape aesthetics.
#' @param width,height,units Plot size in units ("in", "cm", "mm", or "px"). If not supplied, uses the size of current graphics device.
#' @param format,dpi saving format (pdf or png) and png dpi.
#'
#' @author Thomas Chalaux Clergue
#'
#' @export
graph.op <- function(obs, pred, data, path, save.path, note, acceptance, labels = FALSE, text = FALSE, stats = FALSE, pt.colour, ln.colour, pt.pch = 1, units = c("cm"), width = 12, height = 12, format = c("pdf", "png"), dpi = 300){

  require(ggplot2)

  if(missing(pt.colour)){ pt.colour <- "black" }
  if(missing(ln.colour)){ ln.colour <- "blue" }

  if(!missing(obs) & !missing(pred)){

  }else if(!missing(data)){


  }else if(!missing(path)){
    # Look for Observation vs. Prediction file and statistisques
    files <- list.files(path, pattern = "*.csv") # all file ending with .csv
    OP <- read.csv(paste(path, files[grepl(files, pattern = "ObsPred")], sep="/")) # obs vs pred
    if(ncol(OP)==1){
      OP <- read.csv(paste(path, files[grepl(files, pattern = "ObsPred")], sep="/"), sep=";") # obs vs pred
    }
    stats.df  <- read.csv(paste(path, files[grepl(files, pattern = "stats")], sep="/")) # stats
    if(ncol(stats.df) == 1){
      stats.df  <- read.csv(paste(path, files[grepl(files, pattern = "stats")], sep="/"), sep=";") # stats
    }


    # for each type of data
    for(type in levels(as.factor(stats.df$Type))){
      for(grp in levels(as.factor(stats.df$Group))){
        plt <- ggplot() + aes(x = OP[[colnames(OP)[grepl(grp, colnames(OP)) & grepl("Obs", colnames(OP))]]],
                              y = OP[[colnames(OP)[grepl(grp, colnames(OP)) & grepl(type,  colnames(OP))]]]) +
          geom_point(shape = pt.pch, colour = pt.colour) +
          # 1:1 line
          geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
          ## regression line
          geom_smooth(method = "loess", formula = y~x, se = FALSE, colour = ln.colour) +
          # scale graph
          scale_x_continuous("Observed", limits = c(0, 1), breaks = seq(0, 1, .2)) +
          scale_y_continuous("Predicted", limits = c(0, 1), breaks = seq(0, 1, .2)) +
          # theme
            #theme_classic() +
          theme_bw() + theme(legend.position = "none", axis.title = element_text(size = 13), axis.text.y = element_text(size = 12), axis.text.x = element_text(size = 12), panel.grid = element_line(linewidth = 0.5), axis.ticks = element_line(linewidth = 0.3))

        if(!missing(acceptance)){
          plt <- plt +
            geom_abline(slope = 1, intercept = acceptance, linetype = "dotted") +
            geom_abline(slope = 1, intercept = -acceptance, linetype = "dotted")
        }
        if(isTRUE(labels)){
          plt <- plt + geom_label(label = OP$mix.names, size = 1.8)
        }
        if(isTRUE(text)){
          plt <- plt + geom_text(label = OP$mix.names, size = 1.8, nudge_y = 0.02, check_overlap = TRUE)
        }
        if(isTRUE(stats)){
          plt <- plt + annotate(geom = "text", x = 0.0, y = 0.95, hjust = 0,
                                label = paste( paste("ME =",   stats.df$ME[which(stats.df$Type == type & stats.df$Group == grp)]),
                                               paste("RMSE =", stats.df$RMSE[which(stats.df$Type == type & stats.df$Group == grp)]), sep = "\n")) +
            annotate(geom = "text", x = 0.0, y = 0.865, hjust = 0, label = paste(expression("r^{2} =="), stats.df$r2[which(stats.df$Type == type & stats.df$Group == grp)]), parse = T) +
            annotate(geom = "text", x = 0.0, y = 0.815, hjust = 0, label = paste("NSE =", stats.df$NSE[which(stats.df$Type == type & stats.df$Group == grp)]))
        }
        file.name <- paste("OP", type, grp, sep = "_")
        if(!missing(note)){
          file.name <- paste(file.name, note, sep = "_")
        }

        if(missing(save.path)){
          save.path <- path
        }

        if("pdf" %in% format){
          ggsave(filename = paste0(file.name, ".pdf"), plot = plt, path = save.path, units = units, width = width, height = height)
        }
        if("png" %in% format){
          ggsave(filename = paste0(file.name, ".png"), plot = plt, path = save.path, units = units, width = width, height = height, dpi = dpi)
        }

      }
    }
  }
}

